name: sanctuary_l10n_core_example
description: Demonstrates how to use the sanctuary_l10n_core package.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # This is the key part: it tells the example app
  # to use the package from the parent directory.
  sanctuary_l10n_core:
    path: ../

dev_dependencies:
  build_runner: ^2.4.0
  test: ^1.24.0
  lints: ^2.0.0
  build: ^2.4.0
  build_test: ^2.2.0
  path: ^1.8.3
