# The pubspec has been updated with the necessary build dependencies.

name: sanctuary_l10n_core
description: A pure Dart localization toolkit for queer communities, providing a glossary and tools for handling grammatical gender to make inclusive language the default.
version: 0.5.0 
homepage: https://github.com/your_username/sanctuary_l10n_core 
repository: https://github.com/your_username/sanctuary_l10n_core 

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: ^0.18.0
  build_test: ^3.2.1

dev_dependencies:
  test: ^1.24.0
  lints: ^2.0.0
  build: ^2.4.0
  build_runner: ^2.4.0
  path: ^1.8.3 
